## the purpose of the makeCacheMatrix function is to create a matrix (x), but also to create functions that:
## cache the solution of x in the object m, if x has been solved (NULL otherwise) 
## the purpose of the cacheSolve function is to solve the matrix (x) 
## it recognizes whether a solution (m) of the matrix (x) already exists in the makeCacheMatrix function
## if so, it imports the solution using the getsolve function that resides in the makeCacheMatrix function
## if not, it solves the matrix x using the solve(data, ...) function and returns the solution
## storing it in the cache of makeCacheMatrix function


##makeCacheMatrix generates a matrix (x) and functions needed to store and its solution in the cache
makeCacheMatrix <- function(x = matrix()) {
        m <- NULL #assigning a NULL value to the object storing the solved matrix inside the makeCacheMatrix function
        set <- function(y) { #defining set function, which:
                x <<- y #assigns the value y to the object x in the cacheSolve function
                m <<- NULL #assigns a NULL value to the object storing the solved matrix in the cacheSolve function
        }
        get <- function() x
        setsolve <- function(solve) m <<- solve #setsolve is a function assigning the value of the solved matrix to the object m
        getsolve <- function() m #getsolve is a function retrieving the value of the solution
        list(set = set, get = get, #this list contains the set, get, setsolve and getsolve funcs
             setsolve = setsolve,
             getsolve = getsolve)
}


## cacheSolve solves the matrix (x) if not already solved, if already solved
## it retrieves the solution from the cache in the makeCacheMatrix function
cacheSolve <- function(x, ...) { #cacheSolve takes the matrix generated by makeCacheMatrix (x) as an argument
        m <- x$getsolve() #assigning cached value of matrix-solution to the object m (from cache in makeCacheMatrix function)
        if(!is.null(m)) { #if m is not null (i.e. matrix has already been solved):
                message("getting cached data")
                return(m) #the solution is imported from the cache of the makeCacheMatrix function
        }
        data <- x$get() #if the matrix has not already been solved (i.e. m equals NULL), the matrix (x) is imported using the get function
        m <- solve(data, ...) #and subsequently solved using the solve function
        x$setsolve(m) #thereafter, the value of the solved matrix is assigned to the object storing the solution (m)
        m #m is returned at the end of the function (i.e. cacheSolve always returns the solution to the matrix)
}
